"""followers

Revision ID: 34f2334e9939
Revises: 7732d5d6c422
Create Date: 2018-06-22 02:53:08.118334

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34f2334e9939'
down_revision = '7732d5d6c422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
